### ISSUE TITLE
Allow for a higher temporary file limit

### ISSUE THREAD

**Issue by sylv** [sylv/micro#28]
```yaml
# fall-through list of limits, shorter ages = higher priority
limits:
  - age: 7d # limit for files that expire after 7 days
    limit: 1GB
  - age: 30d # limit for files that expire after 30 days 
    limit: 500MB
  - limit: 100MB # default for all files
  ```
